# Generated by Django 4.0.5 on 2022-06-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='train',
            fields=[
                ('train_id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_station', models.CharField(max_length=50)),
                ('end_station', models.CharField(max_length=50)),
                ('dept_time', models.TimeField()),
                ('arr_time', models.TimeField()),
                ('total_seats', models.IntegerField(max_length=250)),
                ('train_name', models.CharField(max_length=50)),
            ],
        ),
    ]
