# Generated by Django 4.0.5 on 2022-06-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='total_seats',
            field=models.IntegerField(default=250),
        ),
    ]
