# Generated by Django 4.0.3 on 2022-07-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_alter_train_total_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_name', models.CharField(max_length=50)),
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=10)),
            ],
        ),
    ]
